### ISSUE TITLE
Version 1.2.0.0. incompatible with EK 7.3.0

### ISSUE THREAD

**Issue by connosco** [opendistro-for-elasticsearch/alerting-kibana-plugin#100]
Hi guys

Starting with this amazing world... I have my first question. I was trying to find something to make alerts in Kibana, I tried with version 1.2.0.0 from Opendistro but i get an incompatibility error, it only can be installed on 7.2.0

Do you know if there is a new released?

BR

**Comment by dbbaughe** [comment]
Hi @connosco,

Version 1.2.0.0 targets Elastic/Kibana versions 7.2
We will be releasing version 1.3.0.0 in the future which will support version 7.3

**Comment by sheldonrong** [comment]
@dbbaughe do you have a roadmap for support on EK 7.3.x and 7.4.x

**Comment by dbbaughe** [comment]
1.3 which supports 7.3 was released and 1.4/7.4 was also released.
In general for ODFE we try to release a matching version to every elasticsearch minor version (major.minor) within a reasonable timeframe.
