### ISSUE TITLE
No logs for alert failures

### ISSUE THREAD

**Issue by achyutaNemani** [opendistro-for-elasticsearch/alerting-kibana-plugin#101]
I am not seeing an easy way to debug the failure of an alert. It shows that the alert/trigger has failed but not able to determine the cause of the failure.

I suggest that be made more intuitive and easier to debug

**Comment by lucaswin-amzn** [comment]
Duplicate of: https://github.com/opendistro-for-elasticsearch/alerting-kibana-plugin/issues/102

Lets use issue #102 for full debug improvement / enhancement.
