### ISSUE TITLE
Issues in Creating Monitor

### ISSUE THREAD

**Issue by naveenkumart28** [opendistro-for-elasticsearch/alerting-kibana-plugin#104]
Hi, 
I am using Vanilla Kibana installed with Open distro alerting-kibana-plugin - 0.7.0.0 with AWS Elastic Search 6.5.4 (Updated with Open distro Elastic Search alerting Plugin)
While Creating monitor, Details about Schedule and Monitor Definition (either Extraction Query/Visual Graph) are formed under `ui_metadata` and are sent along with create request.

But while fetching the monitor details, this `ui_metadata` part is lost. Hence, Fetching the monitor shows default values (like 1 Minute as interval, and Visual Graph is repalced with Extraction Query)

Kindly show some insights

**Comment by dbbaughe** [comment]
For reference: The Kibana plugin sends "user-agent: Kibana" to the Elasticsearch plugin. If that user-agent is not on the request then the ui_metadata is not returned in the response.
