### ISSUE TITLE
Compatibility with Elastic 7.4.2

### ISSUE THREAD

**Issue by nvgoldin** [opendistro-for-elasticsearch/alerting-kibana-plugin#114]
Same as https://github.com/opendistro-for-elasticsearch/alerting/issues/126 - are there any plans to add support for it?

**Comment by dbbaughe** [comment]
Hi @nvgoldin,

Support for 7.4.2 was added in this PR:
https://github.com/opendistro-for-elasticsearch/alerting-kibana-plugin/pull/113

It should be merged and releases cut for 7.4.2 soon.
