### ISSUE TITLE
Guide to install Alerts on the top of existing ELK 7.x

### ISSUE THREAD

**Issue by purk4** [opendistro-for-elasticsearch/alerting-kibana-plugin#116]
I am looking for a step by step installation guide on how to install Alterting plugin on the top of the existing Elasticsearsh and Kibana?

When I looked both **alerting** **and alerting-kibana-plugin** descriptions then I saw that I had to build it from source using Gradle.

The plugin has a great value for many users. 

I am looking for a walkthrough guide on how to install the Alerting plugin on the top of existing ELK.

**Comment by GiviMAD** [comment]
I used this docker files for creating images with the plugin. I hope this helps.
```
FROM docker.elastic.co/elasticsearch/elasticsearch:7.6.1
RUN cd /tmp && \
curl -L -O https://github.com/opendistro-for-elasticsearch/alerting/releases/download/v1.6.0.0/opendistro_alerting-1.6.0.0.zip && \
cd /usr/share/elasticsearch && \
elasticsearch-plugin install --batch file:///tmp/opendistro_alerting-1.6.0.0.zip && \
rm -rf /tmp/*
```
```
FROM docker.elastic.co/kibana/kibana:7.6.1
USER root
RUN cd /tmp && \
curl -L -O https://github.com/opendistro-for-elasticsearch/alerting-kibana-plugin/releases/download/v1.6.0.0/opendistro-alerting-1.6.0.0.zip && \
cd /opt/kibana && \
/opt/kibana/bin/kibana-plugin --allow-root install file:///tmp/opendistro-alerting-1.6.0.0.zip && \
/opt/kibana/bin/kibana --allow-root --optimize && \
rm -rf /tmp/* && \
chown -R kibana /opt/kibana
USER kibana
```

**Comment by dbbaughe** [comment]
There is documentation available here to install plugins, let us know if this doesn't cover enough details, where you get stuck, and we can try to add more information.
https://opendistro.github.io/for-elasticsearch-docs/docs/install/plugins/#install-plugins
