### ISSUE TITLE
Cant select email destination - [illegal_state_exception] Type should

### ISSUE THREAD

**Issue by HimuraKenshin240** [opendistro-for-elasticsearch/alerting-kibana-plugin#117]
Hello, I tried to change the Files in order to add the e-mail and after i try to add a Destination as email i got an error:
[illegal_state_exception] Type should be one of the [chime, slack, custom_webhook, test_action]'
did someone have the same problem?

Thanks in advance.

**Comment by remioo** [comment]
If you changed only the Kibana plugin, this is due to the elasticsearch alerting plugin not supporting email destination.
There is a pull request implementing it here: https://github.com/opendistro-for-elasticsearch/alerting/pull/102

**Comment by HimuraKenshin240** [comment]
> If you changed only the Kibana plugin, this is due to the elasticsearch alerting plugin not supporting email destination.
> There is a pull request implementing it here: [opendistro-for-elasticsearch/alerting#102](https://github.com/opendistro-for-elasticsearch/alerting/pull/102)

**Comment by HimuraKenshin240** [comment]
> If you changed only the Kibana plugin, this is due to the elasticsearch alerting plugin not supporting email destination.
> There is a pull request implementing it here: [opendistro-for-elasticsearch/alerting#102](https://github.com/opendistro-for-elasticsearch/alerting/pull/102)

Remioo thank you for the information, i will give a try!!.

Best Regards
