### ISSUE TITLE
Clicking a filtered field in OfExpression when creating a visual graph monitor throws an error

### ISSUE THREAD

**Issue by dbbaughe** [opendistro-for-elasticsearch/alerting-kibana-plugin#12]
Original issue:
https://discuss.opendistrocommunity.dev/t/define-monitor-using-visual-graph-went-wrong/312

**To replicate:**
Search in input box and click one of the results

**Workaround for now:**
Don't use the search filter or use search filter w/ arrow keys and enter

This seems to be happening inside the Eui Combobox component when calling findPopoverPosition. Need to look into why this is happening.

**Comment by mihirsoni** [comment]
Reproducible from EUI library 5.1.0 which is consumed by OD 0.7.0.0
 
https://codesandbox.io/s/k5kq8qvzz7

**Comment by mihirsoni** [comment]
This is no longer issue in latest version.
