### ISSUE TITLE
URL validation for custom webhooks is incorrect

### ISSUE THREAD

**Issue by lucaswin-amzn** [opendistro-for-elasticsearch/alerting-kibana-plugin#14]
The validation for custom webhooks located here:
https://github.com/opendistro-for-elasticsearch/alerting-kibana-plugin/blob/master/public/pages/Destinations/components/createDestinations/CustomWebhook/validate.js#L18-L26

Does not allow specifying IPs and must be a valid DNS when in reality it could be different.

**Comment by ricardobessa1** [comment]
Hello @lucaswin-amzn , do you want to add support to accept URL with hostname, ipv4 and ipv6 in this function? I can change the regex to validate that if you like.

**Comment by mihirsoni** [comment]
@ricardobessa1 Sure. Let me know. Feel free to create pull request.

**Comment by mihirsoni** [comment]
Fixed by #67
