### ISSUE TITLE
Trigger Action cann‘t get some value

### ISSUE THREAD

**Issue by Joy-Panda** [opendistro-for-elasticsearch/alerting-kibana-plugin#153]
In a trigger, i set Action Message like:
`Monitor {{ctx.monitor.name}} just entered alert status. Please investigate the issue.
Count: {{ctx.results[0].hits.total.value}}`
but {{ctx.results[0].hits.total.value}} is empty

**Comment by KalluriGururaghavendra** [comment]
Hi joy-panda
set your message as 
Count: {{ctx.results.0.hits.total.value}}
It will work
