### ISSUE TITLE
What does "ignored state" mean?

### ISSUE THREAD

**Issue by leejongpyo** [opendistro-for-elasticsearch/alerting-kibana-plugin#155]
Hi,  
There are items "ignored state" while using the alert monitor. 
But when are they counted?
In my case Ignored is counted after completed state. 
Is this normal?

![image](https://user-images.githubusercontent.com/40311906/83085791-e3dbf280-a0c7-11ea-92ff-7549bd8ef0b5.png)

There is no explanation for "ignored state" in "Open Distro for Elasticsearch" Docs page.
- https://opendistro.github.io/for-elasticsearch-docs/docs/alerting/monitors/#work-with-alerts

![image](https://user-images.githubusercontent.com/40311906/83085802-ec342d80-a0c7-11ea-9566-285957d8dff8.png)

**Comment by dbbaughe** [comment]
Hi @leejongpyo,

Sorry for the late response; ignored is not an actual state on the Alert but just information we provide on the table.
The semantics are an alert that is Completed, but was not Acknowledged.
