### ISSUE TITLE
Missing documentation for Mail destination

### ISSUE THREAD

**Issue by vnil1994** [opendistro-for-elasticsearch/alerting-kibana-plugin#191]
Hi,

We're having issues configuring the newly released MAIL destination for alerts. When we try to send a test alert we get the following error in the elasticsearch logs:

"[2020-10-01T10:21:59,446][INFO ][c.a.o.a.m.d.Destination  ] [test-es01] Message published for action name: victor, messageid: Invalid Addresses, statuscode: 1"

We've tried looking up what this error message means but we've found no documentation on the MAIL destination.

Also, how do we specify the authentication details for connecting to our smtp-relay?

Thanks

**Comment by qreshi** [comment]
Hi @vnil1994 ,

The documentation is currently being drafted, will update here once it is available.

A couple things that may help you debug this issue in the meantime though:
1. The information provided by `messageid` is related to JavaMail which is what is being used to send the email, you can look into those to get some insight, it might be due to incorrect configuration for that particular email ([here is an example of using Gmail for sending emails through SMTP](https://support.google.com/a/answer/176600?hl=en))
2. To provide authentication information such as `username` and `password`, you'll need to add the following settings in the Elasticsearch keystore. We'll be looking into different secure store solutions in the future but for now this is the only option:
```
./bin/elasticsearch-keystore add opendistro.alerting.destination.email.<sender_name>.username
./bin/elasticsearch-keystore add opendistro.alerting.destination.email.<sender_name>.password
```

Note: The `<sender_name>` should be replaced with the name of the sender you've configured

Hope this helps!

**Comment by vnil1994** [comment]
Hi @qreshi ,

Thank you for the pointers! I think i've found the issue and it's a combination of us hosting ODFE on kubernetes. We have to somehow add these:

```
./bin/elasticsearch-keystore add opendistro.alerting.destination.email.<sender_name>.username
./bin/elasticsearch-keystore add opendistro.alerting.destination.email.<sender_name>.password
```

to the keystore at boot before elasticsearch is starting (with an init container) or beforehand and then mount in the keystore with the added parameters.

**Comment by qreshi** [comment]
No problem!

Also, if it helps at all, we've made these settings reloadable so if you need to add them at some later time or want to change the values you can run the aforementioned commands to update the values and then call the reload API:

```
POST _nodes/reload_secure_settings
{
  "secure_settings_password": "passwordIfYouKeystoreHasOne" 
}
```

The `secure_settings_password` parameter only needs to be provided if your keystore is password protected.

**Comment by vnil1994** [comment]
I did not know that, thats very good to know.

I tried to add the username and password to the keystore like this:

```
./bin/elasticsearch-keystore add opendistro.alerting.destination.email.mail.username
./bin/elasticsearch-keystore add opendistro.alerting.destination.email.mail.password
```

And then i reloaded the configuration via Dev tools:

`POST _nodes/reload_secure_settings` (We have no password on the keystore)

But i still get the "[2020-10-01T10:21:59,446][INFO ][c.a.o.a.m.d.Destination ] [test-es01] Message published for action name: victor, messageid: Invalid Addresses, statuscode: 1" error. 

We're using an internal SMTP relay which requires authentication and from what we can see, the issue is that the ODFE still does not try to authenticate itself via username and password.

Any ideas?

**Comment by qreshi** [comment]
Could you try to provide more information on your setup and the configuration of your email sender?

Given the error is `Invalid Addresses`, it could be possible that the recipient addresses are the ones that are incorrect and the SMTP relay is unable to send to them.

**Comment by vnil1994** [comment]
Hi @qreshi sorry for the delay.

We can see the following in our SMTP relay log:

`<22>Oct  6 10:47:06 smtp-srv01 postfix/smtpd[19272]: NOQUEUE: reject: RCPT from unknown[192.168.1.10]: 554 5.7.1 <victor@example.com>: Relay access denied; from=<opendistro@example.com> to=<victor@example.com> proto=ESMTP helo=<opendistro-es01-695f5d8855-244fk>`

So it's still seems that the authentication is the problem. We've also verified that the routing and firewall are correctly setup.

![destination](https://user-images.githubusercontent.com/48046901/95180645-8b79d780-07c2-11eb-864c-d622ef88647f.png)

![mail-senders](https://user-images.githubusercontent.com/48046901/95180651-903e8b80-07c2-11eb-8ca0-f44a29920fe2.png)

![mail-group](https://user-images.githubusercontent.com/48046901/95180662-92a0e580-07c2-11eb-9bf5-0868873ab7d7.png)

**Comment by qreshi** [comment]
Glad you were able to get that figured out.

Also, just a heads up, [the documentation has been updated for email destination](https://opendistro.github.io/for-elasticsearch-docs/docs/alerting/monitors/#email-as-a-destination)

**Comment by vnil1994** [comment]
Thank you for all your help.
