### ISSUE TITLE
Check if the aggregation value is null before comparing threshold in painless script

### ISSUE THREAD

**Issue by dbbaughe** [opendistro-for-elasticsearch/alerting-kibana-plugin#22]
Currently we just do a comparison of the aggregation.when.value and the threshold, but if there were no matching documents, the aggregation value is null and painless will throw an error when doing null > x.

**Comment by Jon-AtAWS** [comment]
The resulting behavior is that we continuously throw alerts when there's no data (e.g.). We should not alert when there are errors with the query.

**Comment by dbbaughe** [comment]
This was merged in #38
