### ISSUE TITLE
Add "Where" clause to visual editor for monitors

### ISSUE THREAD

**Issue by elfisher** [opendistro-for-elasticsearch/alerting-kibana-plugin#23]
We should add a where clause to the visual editor when creating a monitor to make it easier for users to be able to add a condition to their chart. For example being able to do `WHEN count() OF response OVER all documents FOR THE LAST 5 minutes **where response_code >= 400**`

**Comment by mihirsoni** [comment]
Matrix for the supports of operator with ES datatypes

| "Operator"             | "dataTypes"                   | 
|------------------------|-------------------------------| 
| "is"                   | "number,text,keyword,boolean" | 
| "is not"               | "number,text,keyword,boolean" | 
| "is null"              | "number,text,keyword,boolean" | 
| "is not null"          | "number,text,keyword"         | 
| "is grater than"       | "number"                      | 
| "is grater than equal" | "number"                      | 
| "is less than"         | "number"                      | 
| "is less than equal"   | "number"                      | 
| "is in range"          | "number"                      | 
| "is not in range"          | "number"                      | 
| "starts with"          | "text,keyword"                | 
| "ends with"            | "text,keyword"                | 
| "contains"             | "text,keyword"                | 
| "does not contains"    | "text"                        |
