### ISSUE TITLE
Disable the Query parameter box in Custom webhook

### ISSUE THREAD

**Issue by mihirsoni** [opendistro-for-elasticsearch/alerting-kibana-plugin#24]
While creating Custom webhook, Query Parameter editor is enabled by default in either case of URL selection (i.e fully qualified URL , custom (host /port/path)  which creates confusion and customer provide Query parameter in editor instead of URL.

To aligned with Slack / Chime we should consider the endpoint to be fully qualified URL.

This will require to disable Query parameter editor in case user has chosen endpoint and no custom URL.

More details on : https://discuss.opendistrocommunity.dev/t/alerting-webhook-destination/295/

**Comment by dreamer-89** [comment]
@mihirsoni : Can I take up this issue ?

**Comment by mihirsoni** [comment]
@dreamer-89 sounds good :) Thanks for informing.

**Comment by ricardobessa1** [comment]
Hello @dreamer-89 ,
How is going with that issue? Are you still working on this or need any help?

**Comment by mihirsoni** [comment]
@ricardobessa1  I think you could take it up. There shouldn't be any issue.

**Comment by ricardobessa1** [comment]
Hello @mihirsoni,
I made some tests and want to be sure if is the desired state before I send the pull request:
- Currently the initial state of Query Parameters is an array with one empty string key/value;
- If user choose **Define endpoint by URL** I'm following the behavior of other inputs of custom attribute URL, reverting back to initial state and setting the key/values as disabled.
- Only validate the query parameters if custom attribute URL is set. If keep validating even when **Webhook URL** is set then the validation of query parameters will block the user to save.

**Comment by mihirsoni** [comment]
@ricardobessa1 

Yes, we should avoid validating queryParams in case of Define by URL.
