### ISSUE TITLE
Error while updating a monitor

### ISSUE THREAD

**Issue by Jeeppler** [opendistro-for-elasticsearch/alerting-kibana-plugin#26]
While updating a monitor and trying to create a different alert rule in the graphical editor I received the following error:

![alert-error](https://user-images.githubusercontent.com/2007739/55649621-0c5cab00-57a9-11e9-8f39-26910661da94.png)

I am running an ElasticSearch Server cluster in US Oregon and software version `R20190221`.

**Comment by mihirsoni** [comment]
Hi @Jeeppler 

Thanks for reporting issue. 

Are you getting this error from performing action (Related #12) on visual graph  then it is known issue.

If not, could you provide a steps to reproduce ?

**Comment by Jeeppler** [comment]
@mihirsoni yes, they seem to be the same.

**Comment by mihirsoni** [comment]
Thanks for confirming. We are still looking into that. There is a workaround for now. I'll close this in favor of #12 so we can track it better.

**Workaround for now:**
Don't use the search filter or use search filter w/ arrow keys and enter
