### ISSUE TITLE
Compatibility for Elastic Stack Basic

### ISSUE THREAD

**Issue by kvv5150** [opendistro-for-elasticsearch/alerting-kibana-plugin#27]
Has anyone had any success getting this plugin to work with the Basic license? I'm not sure what all is involved but I know that generally the plugin cannot create incides with a "." in them. But obviously other plugin maintainers have done it.

**Comment by mihirsoni** [comment]
@kvv5150 Could you provide more details on what is an issue you're facing while using with different stack ?

**Comment by kvv5150** [comment]
I can install the alerting plugin with the Basic Elastic license but when I save an alert, nothing happens. When I run "journalctl -u kibana.service" I see "index not found .opendistro-alerting-config". Seems to be a permissions issue with the plugin not being able to create that index with elasticsearch. Tested on 6.5.4

**Comment by mihirsoni** [comment]
@kvv5150 did you made sure you've installed backend plugin @opendistro-for-elasticsearch/alerting on your Elasticsearch cluster.

**Comment by kvv5150** [comment]
Oh, no I didn't! I extracted the plugin directly from the Docker container.
How do I go about installing it?

**Comment by mihirsoni** [comment]
@kvv5150 There is no recommend way as of now, you will have compile the code as mentioned in [README.md](https://github.com/opendistro-for-elasticsearch/alerting/blob/master/README.md#build) and try it out.
