### ISSUE TITLE
PDF generation

### ISSUE THREAD

**Issue by CannibalKush** [opendistro-for-elasticsearch/alerting-kibana-plugin#3]
Hi, a much-sought after feature in Kibana with X-Pack is the ability to export dashboards and visualizations as PDF.

Does OpenDistro Kibana support this feature? If not, is it currently on the roadmap?

Thanks for your time.

**Comment by dbbaughe** [comment]
Hi,

Currently we do not support this feature, but I've added it to the backlog for you:
https://github.com/opendistro-for-elasticsearch/community/issues/16

Thanks for the request, will close this in favor of the above issue.
