### ISSUE TITLE
Clarify the monitor creation text for visual editor

### ISSUE THREAD

**Issue by elfisher** [opendistro-for-elasticsearch/alerting-kibana-plugin#33]
Currently the text follows this pattern `Match the following condition
WHEN sum()
OF select a field
OVER all documents
FOR THE LAST 1 hour(s)`

This reads like a trigger but it for a monitor. We can revamp the text for clarity.

**Comment by stevensideyliu** [comment]
Instead of `Match the following condition` we should replace to text with `Create a monitor with the following condition WHEN sum()
OF select a field
OVER all documents
FOR THE LAST 1 hour(s)`

**Comment by elfisher** [comment]
@stevensideyliu let's remove the condition word altogether. Maybe we can co `Create a monitor for sum() of select a field OVER all documents FOR THE LAST 1`?

**Comment by elfisher** [comment]
@aetter have any thoughts on this?

**Comment by aetter** [comment]
Sure, maybe `Check for`? As in, `Check for WHEN count() OVER all documents FOR THE LAST 1 hour(s)`?

I'm also fine with `Check`, `Check for the following`, `Create a monitor for`.

**Comment by elfisher** [comment]
let's go with `Create a monitor for sum() of select a field OVER all documents FOR THE LAST 1`. @mihirsoni and @stevensideyliu does that sound good?

**Comment by mihirsoni** [comment]
@elfisher sounds good.
