### ISSUE TITLE
Error when i trying install as plugin

### ISSUE THREAD

**Issue by OpakAlex** [opendistro-for-elasticsearch/alerting-kibana-plugin#40]
```
bash-4.2$ bin/kibana-plugin install https://github.com/opendistro-for-elasticsearch/alerting-kibana-plugin/archive/v0.8.0.0.zip
Attempting to transfer from https://github.com/opendistro-for-elasticsearch/alerting-kibana-plugin/archive/v0.8.0.0.zip
Transferring unknown number of bytes
Transfer complete
Retrieving metadata from plugin archive
Plugin installation was unsuccessful due to error "No kibana plugins found in archive"
```
What i am doing wrong? 
I want use original kibana from elasticsearch, and install some opendistro plugins. It's possible?

**Comment by dbbaughe** [comment]
Hi @OpakAlex,

That artifact seems to be the zip of the source code and not the actual plugin distribution zip.
Here is a link to the plugin zip you should install:
https://d3g5vo6xdbdb9a.cloudfront.net/downloads/kibana-plugins/opendistro-alerting/opendistro-alerting-0.8.0.0.zip

Here is a link to installing individual plugins:
https://opendistro.github.io/for-elasticsearch-docs/docs/install/plugins/

(It seems to be missing documentation around Kibana plugin installations, we will fix this)

**Comment by OpakAlex** [comment]
yes, thanks!

**Comment by divyankm** [comment]
I am getting same error while installing standalone kibana 7.8.0 OD alerting plugin version 1.9.0.0,Pls help...
![image](https://user-images.githubusercontent.com/80899863/120146738-2d8f7980-c203-11eb-9db2-69a143c92ddc.png)
