### ISSUE TITLE
Incorrect plugin name for uninstalling

### ISSUE THREAD

**Issue by parallelthought** [opendistro-for-elasticsearch/alerting-kibana-plugin#52]
While trying to uninstall the plugin from Kibana, it is not possible to uninstall using the display name of the plugin. Instead it is required to remove the version and uninstall for it to be removed.

Kibana version: 6.7.1 (non-OSS)
Alerting: 0.9.0

The plugin should be displayed without it's version while being listed. This would make it consistent with other plugins.

The above error is not observed with the Elasticsearch plugin as it does not display the version along with it's name.

**Command logs**
```
bin/kibana-plugin list
opendistro-alerting@0.9.0.0

bin/kibana-plugin remove opendistro-alerting@0.9.0.0
Unable to remove plugin because of error: "Plugin [opendistro-alerting@0.9.0.0] is not installed"

sudo bin/kibana-plugin remove opendistro-alerting
Removing opendistro-alerting...
Plugin removal complete

```

**Comment by mihirsoni** [comment]
@parallelthought 
Thanks for reporting this issue. This is how `bin/kibana-plugin list` command works it display plugin name and version with it `plugin-name@version` I think it makes sense to show list with the version of plugin. I will be closing this as it is not related to this plugin but how overall plugin infrastructure works for Kibana.
