### ISSUE TITLE
Wrong size parameter for fetching Destinations in creation of Trigger UI.

### ISSUE THREAD

**Issue by abhijithshivaswamy** [opendistro-for-elasticsearch/alerting-kibana-plugin#70]
Hi, while creating Trigger, the list of destinations is fetched using this query 
**https://kibana.example.com:5601/api/alerting/destinations?_searchsize=200_**

The API does not respect the "searchsize parameter", hence, even though i have 30+ destinations, it will fetch only 20, which is default Elasticsearch return size.

The right parameter would be "size", which would fetch the number of given destinations.
**https://kibana.eample.in:5601/api/alerting/destinations?_size=200_**

 
I am running **Opendistro 0.9.0.0** and **ES version 6.7.1**

**Comment by dbbaughe** [comment]
Hi @abhijithshivaswamy,

Thanks for reporting this issue.
It seems to be a simple bug located at:
https://github.com/opendistro-for-elasticsearch/alerting-kibana-plugin/blob/master/public/pages/CreateTrigger/containers/ConfigureActions/ConfigureActions.js#L57
```
const response = await httpClient.get(
    `../api/alerting/destinations?search${searchText}size=200`
);
```

Seems there is no equals between search and searchText and no & between search and size.
