### ISSUE TITLE
Support for Kibana 7.2.x

### ISSUE THREAD

**Issue by nerddelphi** [opendistro-for-elasticsearch/alerting-kibana-plugin#79]
Hi.

Could you provide a release for Kibana 7.2.x ?

**Comment by dbbaughe** [comment]
Hi @nerddelphi,

We are currently working on the alerting release for Kibana 7.2.x, it should be available this week.

Drew

**Comment by dbbaughe** [comment]
https://github.com/opendistro-for-elasticsearch/alerting-kibana-plugin/pull/81
