### ISSUE TITLE
Does this plugin support other languages other than "mustache" and "painless"

### ISSUE THREAD

**Issue by ionutale** [opendistro-for-elasticsearch/alerting-kibana-plugin#86]
Does this plugin support other languages other than "mustache" and "painless" ?

i can't find other in the source code

**Comment by dbbaughe** [comment]
Hi @ionutale,

Currently the only language supported in triggers is painless and for actions we only support mustache. What else are you currently looking for?

**Comment by ionutale** [comment]
i know that mustache is just a templating engine, but a bit of support to js would be nice (even more to a EC6 ).

for example, if i wanna build a json array i endup with 1 extra comma ", " at the last object and this does not pass validation with JSONschema
so i could work around and build 1 extra entry in the array after the {{#arr}} {{/arr}}  

example extra comma:
```
[
    {{#todo}} 
       {"title": title},
   {{/todo}}  
}
```

example extra object at the end:
```
[
    {{#todo}} 
       {"title": title},
   {{/todo}}  
   {"title": null}
}
```

js is a universally supported language, even postman is using it as scripting language, it would be nice if could be used.

let me know what you think

**Comment by lucaswin-amzn** [comment]
Hi @ionutale,

We are not planning on supporting different template languages. We will consider doing a deep dive on supporting more than just `painless` for trigger definitions.

**Comment by celesteking** [comment]
This is absolutely wrong to reject. When opendistro/alerting is used as query execution platform with external service (Destination) doing the notification job, it's essential to be able to pass full query results onto the external service. Currently, this is possible by descending the object tree manually through mustache deep-dive syntax `{{#a.b.c}}{{/a.b.c}}`. This is wrong and is a complete nonsense. There should be a way to just pass the query (either unaltered or a bit brushed up) over to the Destination and just let it deal with that data on its own.
