### ISSUE TITLE
is the list of monitors is running async or sync?

### ISSUE THREAD

**Issue by ionutale** [opendistro-for-elasticsearch/alerting-kibana-plugin#93]
is the list of monitors is running async or sync?
we estimate on creating around 200 monitors that will run every minute, and we are wondering if this is feasible

**Comment by lucaswin-amzn** [comment]
Hi @ionutale,

Your number of monitors depends on your number of nodes and the power of each node. We have done testing with 1,000 monitors and noticed no delayed jobs.

Jobs run async though, as in 3 monitors could be running in parallel if their schedules overlap.
