### ISSUE TITLE
Alerting in kibana.

### ISSUE THREAD

**Issue by bramu-rythmos** [opendistro-for-elasticsearch/alerting-kibana-plugin#96]
Hello team,
While creating the alerts in kibana using extraction query we get no of hits results. for example:
while creating trigger on the first hit I do the below.
ctx.results[0].hits.hits[1]._source.rabbitmq.queue.messages.ready.count>1000

what if there are multiple hits? How do I denote this with iterative?
EX: ctx.results[0].hits.hits[i>0]._source.rabbitmq.queue.messages.ready.count>1000 so that it sends alert for each and every result hit. Is there any way to do that or do we need to create additional triggers like below for each hit?
ctx.results[0].hits.hits[2]._source.rabbitmq.queue.messages.ready.count>1000
ctx.results[0].hits.hits[3]._source.rabbitmq.queue.messages.ready.count>1000
ctx.results[0].hits.hits[4]._source.rabbitmq.queue.messages.ready.count>1000 and so on...

**Comment by celesteking** [comment]
This is thoroughly [explained in docs](https://opendistro.github.io/for-elasticsearch-docs/docs/alerting/monitors/#sample-scripts) .  Also, see feature requests [43](https://github.com/opendistro-for-elasticsearch/alerting/issues/43) and [44](https://github.com/opendistro-for-elasticsearch/alerting/issues/44) . Let's close this.
